<?php
return array(
    'GitPHP_Resource'                             => GITPHP_INCLUDEDIR . 'Resource.class.php',
    \GitPHP\Db_Result::class                      => GITPHP_INCLUDEDIR . 'Result.php',
    'Model_Gitosis'                               => GITPHP_INCLUDEDIR . 'Model_Gitosis.php',
    'GitPHP_Cache'                                => GITPHP_CACHEDIR . 'Cache.class.php',
    'GitPHP_Blob'                                 => GITPHP_GITOBJECTDIR . 'Blob.class.php',
    'GitPHP_BranchDiff'                           => GITPHP_GITOBJECTDIR . 'BranchDiff.class.php',
    'GitPHP_Commit'                               => GITPHP_GITOBJECTDIR . 'Commit.class.php',
    'GitPHP_DiffExe'                              => GITPHP_GITOBJECTDIR . 'DiffExe.class.php',
    'GitPHP_FileDiff'                             => GITPHP_GITOBJECTDIR . 'FileDiff.class.php',
    'GitPHP_FilesystemObject'                     => GITPHP_GITOBJECTDIR . 'FilesystemObject.class.php',
    'GitPHP_GitExe'                               => GITPHP_GITOBJECTDIR . 'GitExe.class.php',
    'GitPHP_GitObject'                            => GITPHP_GITOBJECTDIR . 'GitObject.class.php',
    'GitPHP_Head'                                 => GITPHP_GITOBJECTDIR . 'Head.class.php',
    'GitPHP_Project'                              => GITPHP_GITOBJECTDIR . 'Project.class.php',
    'GitPHP_ProjectList'                          => GITPHP_GITOBJECTDIR . 'ProjectList.class.php',
    'GitPHP_ProjectListArray'                     => GITPHP_GITOBJECTDIR . 'ProjectListArray.class.php',
    'GitPHP_ProjectListArrayLegacy'               => GITPHP_GITOBJECTDIR . 'ProjectListArrayLegacy.class.php',
    'GitPHP_ProjectListBase'                      => GITPHP_GITOBJECTDIR . 'ProjectListBase.class.php',
    'GitPHP_ProjectListDirectory'                 => GITPHP_GITOBJECTDIR . 'ProjectListDirectory.class.php',
    'GitPHP_ProjectListFile'                      => GITPHP_GITOBJECTDIR . 'ProjectListFile.class.php',
    'GitPHP_Ref'                                  => GITPHP_GITOBJECTDIR . 'Ref.class.php',
    'GitPHP_Tag'                                  => GITPHP_GITOBJECTDIR . 'Tag.class.php',
    'GitPHP_TmpDir'                               => GITPHP_GITOBJECTDIR . 'TmpDir.class.php',
    'GitPHP_Tree'                                 => GITPHP_GITOBJECTDIR . 'Tree.class.php',
    'GitPHP_TreeDiff'                             => GITPHP_GITOBJECTDIR . 'TreeDiff.class.php',
    'DiffHighlighter'                             => GITPHP_GITOBJECTDIR . 'DiffHighlighter.php',
    'DiffContext'                                 => GITPHP_GITOBJECTDIR . 'DiffContext.php',
);
